/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author rsbuf
 */
public class MenuView extends javax.swing.JFrame {

    /**
     * Creates new form MenuView
     */
    public MenuView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TituloLabel = new javax.swing.JLabel();
        MenuBar = new javax.swing.JMenuBar();
        BuscaMenu = new javax.swing.JMenu();
        CriarMenu = new javax.swing.JMenu();
        ReceitaItem = new javax.swing.JMenuItem();
        IngrienteReceita = new javax.swing.JMenuItem();
        CompartilharMenu = new javax.swing.JMenu();
        EntrarMenu = new javax.swing.JMenu();
        LoginItem = new javax.swing.JMenuItem();
        CadastroItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TituloLabel.setBackground(new java.awt.Color(0, 0, 0));
        TituloLabel.setDisplayedMnemonic('0');
        TituloLabel.setFont(new java.awt.Font("Segoe UI Historic", 0, 24)); // NOI18N
        TituloLabel.setText("Livro de Receitas");

        BuscaMenu.setText("Busca");
        MenuBar.add(BuscaMenu);

        CriarMenu.setText("Criar");

        ReceitaItem.setText("Receita");
        ReceitaItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReceitaItemActionPerformed(evt);
            }
        });
        CriarMenu.add(ReceitaItem);

        IngrienteReceita.setText("Ingrediente");
        CriarMenu.add(IngrienteReceita);

        MenuBar.add(CriarMenu);

        CompartilharMenu.setText("Compartilhar");
        MenuBar.add(CompartilharMenu);

        EntrarMenu.setText("Entrar");

        LoginItem.setText("Login");
        LoginItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginItemActionPerformed(evt);
            }
        });
        EntrarMenu.add(LoginItem);

        CadastroItem.setText("Cadastro");
        CadastroItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroItemActionPerformed(evt);
            }
        });
        EntrarMenu.add(CadastroItem);

        MenuBar.add(EntrarMenu);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(TituloLabel)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(TituloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReceitaItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReceitaItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReceitaItemActionPerformed

    private void LoginItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginItemActionPerformed
       
        TelaLoginView loginView = new TelaLoginView();
        loginView.setVisible(true);
        
        this.dispose();
        
    }//GEN-LAST:event_LoginItemActionPerformed

    private void CadastroItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroItemActionPerformed
        
        TelaCadastroView loginView = new TelaCadastroView();
        loginView.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_CadastroItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu BuscaMenu;
    private javax.swing.JMenuItem CadastroItem;
    private javax.swing.JMenu CompartilharMenu;
    private javax.swing.JMenu CriarMenu;
    private javax.swing.JMenu EntrarMenu;
    private javax.swing.JMenuItem IngrienteReceita;
    private javax.swing.JMenuItem LoginItem;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenuItem ReceitaItem;
    private javax.swing.JLabel TituloLabel;
    // End of variables declaration//GEN-END:variables
}
