package view;

import controller.IngredienteController;
import controller.ReceitaController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JFormattedTextField;
import javax.swing.table.DefaultTableModel;
import model.IngredienteModel;
import model.ReceitaIngredienteModel;
import model.ReceitaModel;
import model.UsuarioModel;

public class ReceitaView extends javax.swing.JFrame {

    private final ReceitaController receitaController;
    private final IngredienteController ingredienteController;
    private final List<ReceitaIngredienteModel> ingredientesReceita;
    private List<IngredienteModel> ingredientesDisponiveis;
    private DefaultTableModel tableModel;
    private final UsuarioModel usuarioLogado;
    
    public ReceitaView() {
        this(null);
    }

    public ReceitaView(UsuarioModel usuarioLogado) {
        this.usuarioLogado = usuarioLogado;
        this.receitaController = new ReceitaController();
        this.ingredienteController = new IngredienteController();
        this.ingredientesReceita = new ArrayList<>();
        this.ingredientesDisponiveis = new ArrayList<>();

        initComponents();
        configureCategoryComboBox();
        loadIngredientOptions();
        configureIngredientsTable();
        configureModoPreparoAutoWrap();

        setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                // Manter as permissões do usuário logado ao voltar ao menu
                MenuView menu = new MenuView(usuarioLogado);
                menu.setVisible(true);
                dispose();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RolagemScrollPane = new javax.swing.JScrollPane();
        PrincipalPanel = new javax.swing.JPanel();
        TituloPanel = new javax.swing.JPanel();
        TituloLabel = new javax.swing.JLabel();
        CamposPanel = new javax.swing.JPanel();
        NomeIngredienteLabel = new javax.swing.JLabel();
        DescricaoLabel = new javax.swing.JLabel();
        ModoPreparoLabel = new javax.swing.JLabel();
        Sessao1Panel = new javax.swing.JLabel();
        NomeTextField = new javax.swing.JTextField();
        DescricaoScrollPane = new javax.swing.JScrollPane();
        DescricaoTextArea = new javax.swing.JTextArea();
        ModoPreparoScrollPane = new javax.swing.JScrollPane();
        ModoPreparoTextArea = new javax.swing.JTextArea();
        Sessao2Panel = new javax.swing.JLabel();
        SelecaoCategoriaComboBox1 = new javax.swing.JComboBox<>();
        Sessao3Panel = new javax.swing.JLabel();
        SelecaoCategoriaComboBox2 = new javax.swing.JComboBox<>();
        NomeReceitaLabel1 = new javax.swing.JLabel();
        QuantidadeLabel = new javax.swing.JLabel();
        QuantidadeSpinner = new javax.swing.JSpinner();
        IngredienteScrollPane = new javax.swing.JScrollPane();
        IngredientesTable = new javax.swing.JTable();
        AdicionaButton = new javax.swing.JButton();
        RemoverButton = new javax.swing.JButton();
        SalvarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RolagemScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        RolagemScrollPane.setPreferredSize(new java.awt.Dimension(282, 613));

        PrincipalPanel.setPreferredSize(new java.awt.Dimension(292, 850));

        TituloPanel.setBackground(new java.awt.Color(153, 153, 153));
        TituloPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TituloPanel.setForeground(new java.awt.Color(0, 102, 102));
        TituloPanel.setPreferredSize(new java.awt.Dimension(282, 50));
        TituloPanel.setLayout(new java.awt.BorderLayout());

        TituloLabel.setBackground(new java.awt.Color(204, 204, 255));
        TituloLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TituloLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloLabel.setText("CRIAR NOVA RECEITA");
        TituloPanel.add(TituloLabel, java.awt.BorderLayout.CENTER);

        CamposPanel.setPreferredSize(new java.awt.Dimension(282, 465));
        CamposPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NomeIngredienteLabel.setText("NOME:");
        CamposPanel.add(NomeIngredienteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 421, -1, -1));

        DescricaoLabel.setText("DESCRIÇÃO:");
        CamposPanel.add(DescricaoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 70, -1, -1));

        ModoPreparoLabel.setText("MODO DE PREPARO:");
        CamposPanel.add(ModoPreparoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 196, -1, -1));

        Sessao1Panel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Sessao1Panel.setText("RECEITA");
        CamposPanel.add(Sessao1Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 14, -1, -1));

        NomeTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        NomeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeTextFieldActionPerformed(evt);
            }
        });
        CamposPanel.add(NomeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 42, 207, -1));

        DescricaoScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        DescricaoTextArea.setColumns(20);
        DescricaoTextArea.setRows(5);
        DescricaoScrollPane.setViewportView(DescricaoTextArea);

        CamposPanel.add(DescricaoScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 224, 251, -1));

        ModoPreparoScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        ModoPreparoScrollPane.setAutoscrolls(true);
        ModoPreparoScrollPane.setFocusable(false);
        ModoPreparoScrollPane.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ModoPreparoScrollPaneKeyReleased(evt);
            }
        });

        ModoPreparoTextArea.setColumns(20);
        ModoPreparoTextArea.setRows(5);
        ModoPreparoScrollPane.setViewportView(ModoPreparoTextArea);

        CamposPanel.add(ModoPreparoScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 98, 251, -1));

        Sessao2Panel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Sessao2Panel.setText("CATEGORIA");
        CamposPanel.add(Sessao2Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 322, -1, -1));

        SelecaoCategoriaComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione uma opção", "Sobremesa", "Aperetivo", "Bebida", "Salada", "Salgado", "Doce", "Almoço", "Janta" }));
        CamposPanel.add(SelecaoCategoriaComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 356, -1, -1));

        Sessao3Panel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Sessao3Panel.setText("INGREDIENTES");
        CamposPanel.add(Sessao3Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 390, -1, -1));

        SelecaoCategoriaComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione uma opção", "Leite", "Alho", "Costela", "Frango", "Creme de leite", "Ovo", "Sal", "Açucar", "Oleo", " " }));
        CamposPanel.add(SelecaoCategoriaComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 418, -1, -1));

        NomeReceitaLabel1.setText("NOME:");
        CamposPanel.add(NomeReceitaLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 45, -1, -1));

        QuantidadeLabel.setText("QUANTIDADE:");
        CamposPanel.add(QuantidadeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 452, -1, -1));

        QuantidadeSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        CamposPanel.add(QuantidadeSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 452, -1, -1));

        IngredientesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Ingrediente", "Quantidade", "Unidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        IngredientesTable.getTableHeader().setReorderingAllowed(false);
        IngredienteScrollPane.setViewportView(IngredientesTable);

        CamposPanel.add(IngredienteScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 486, 259, 185));

        AdicionaButton.setText("Adicionar");
        AdicionaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarIngredienteReceita();
            }
        });
        CamposPanel.add(AdicionaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 683, -1, -1));

        RemoverButton.setText("Remover");
        RemoverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoverButtonActionPerformed(evt);
            }
        });
        CamposPanel.add(RemoverButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 683, -1, -1));

        SalvarButton.setText("Salvar Receita");
        SalvarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarReceita();
            }
        });
        CamposPanel.add(SalvarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 712, -1, -1));

        javax.swing.GroupLayout PrincipalPanelLayout = new javax.swing.GroupLayout(PrincipalPanel);
        PrincipalPanel.setLayout(PrincipalPanelLayout);
        PrincipalPanelLayout.setHorizontalGroup(
            PrincipalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrincipalPanelLayout.createSequentialGroup()
                .addComponent(CamposPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PrincipalPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(TituloPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        PrincipalPanelLayout.setVerticalGroup(
            PrincipalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrincipalPanelLayout.createSequentialGroup()
                .addComponent(TituloPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CamposPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        RolagemScrollPane.setViewportView(PrincipalPanel);

        getContentPane().add(RolagemScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NomeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                              
        DescricaoTextArea.requestFocus();
    }                                              

    @SuppressWarnings("unused")
    private void AdicionaButtonActionPerformed(java.awt.event.ActionEvent evt) {
        adicionarIngredienteReceita();
    }

    private void RemoverButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        removerIngredienteReceita();
    }                                              

    @SuppressWarnings("unused")
    private void SalvarButtonActionPerformed(java.awt.event.ActionEvent evt) {
        salvarReceita();
    }

    private void ModoPreparoScrollPaneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ModoPreparoScrollPaneKeyReleased
        processarQuebraLinhaModoPreparo();
    }//GEN-LAST:event_ModoPreparoScrollPaneKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReceitaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReceitaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReceitaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReceitaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReceitaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdicionaButton;
    private javax.swing.JPanel CamposPanel;
    private javax.swing.JLabel DescricaoLabel;
    private javax.swing.JScrollPane DescricaoScrollPane;
    private javax.swing.JTextArea DescricaoTextArea;
    private javax.swing.JScrollPane IngredienteScrollPane;
    private javax.swing.JTable IngredientesTable;
    private javax.swing.JLabel ModoPreparoLabel;
    private javax.swing.JScrollPane ModoPreparoScrollPane;
    private javax.swing.JTextArea ModoPreparoTextArea;
    private javax.swing.JLabel NomeIngredienteLabel;
    private javax.swing.JLabel NomeReceitaLabel1;
    private javax.swing.JTextField NomeTextField;
    private javax.swing.JPanel PrincipalPanel;
    private javax.swing.JLabel QuantidadeLabel;
    private javax.swing.JSpinner QuantidadeSpinner;
    private javax.swing.JButton RemoverButton;
    private javax.swing.JScrollPane RolagemScrollPane;
    private javax.swing.JButton SalvarButton;
    private javax.swing.JComboBox<String> SelecaoCategoriaComboBox1;
    private javax.swing.JComboBox<String> SelecaoCategoriaComboBox2;
    private javax.swing.JLabel Sessao1Panel;
    private javax.swing.JLabel Sessao2Panel;
    private javax.swing.JLabel Sessao3Panel;
    private javax.swing.JLabel TituloLabel;
    private javax.swing.JPanel TituloPanel;
    // End of variables declaration//GEN-END:variables
    
    // Métodos auxiliares
    private void configureCategoryComboBox() {
        SelecaoCategoriaComboBox1.removeAllItems();
        SelecaoCategoriaComboBox1.addItem("Selecione uma opção");
        SelecaoCategoriaComboBox1.addItem("Sobremesa");
        SelecaoCategoriaComboBox1.addItem("Aperetivo");
        SelecaoCategoriaComboBox1.addItem("Bebida");
        SelecaoCategoriaComboBox1.addItem("Salada");
        SelecaoCategoriaComboBox1.addItem("Salgado");
        SelecaoCategoriaComboBox1.addItem("Doce");
        SelecaoCategoriaComboBox1.addItem("Almoço");
        SelecaoCategoriaComboBox1.addItem("Janta");
    }
    
    private void loadIngredientOptions() {
        try {
            // Busca todos os ingredientes do banco de dados
            ingredientesDisponiveis = ingredienteController.buscarTodosIngredientes();
            
            // Ordena os ingredientes por nome para facilitar a busca
            if (ingredientesDisponiveis != null) {
                ingredientesDisponiveis.sort((i1, i2) -> i1.getNome().compareToIgnoreCase(i2.getNome()));
            } else {
                ingredientesDisponiveis = new ArrayList<>();
            }
            
            // Limpa o ComboBox e adiciona a opção padrão
            SelecaoCategoriaComboBox2.removeAllItems();
            SelecaoCategoriaComboBox2.addItem("Selecione um ingrediente");
            
            // Se não houver ingredientes no banco, adiciona os padrão
            if (ingredientesDisponiveis.isEmpty()) {
                adicionarIngredientesPadrao();
                return;
            }
            
            // Adiciona cada ingrediente ao ComboBox no formato "Nome (Unidade de Medida)"
            for (IngredienteModel ingrediente : ingredientesDisponiveis) {
                String item = String.format("%s (%s)", 
                    ingrediente.getNome(), 
                    ingrediente.getUnidade_medida());
                SelecaoCategoriaComboBox2.addItem(item);
            }
            
        } catch (Exception e) {
            // Em caso de erro, exibe uma mensagem e limpa a lista de ingredientes
            JOptionPane.showMessageDialog(this, 
                "Erro ao carregar ingredientes: " + e.getMessage(), 
                "Erro", 
                JOptionPane.ERROR_MESSAGE);
            ingredientesDisponiveis = new ArrayList<>();
            
            // Adiciona os ingredientes padrão
            adicionarIngredientesPadrao();
        }
    }
    
    private void adicionarIngredientesPadrao() {
        String[] ingredientesPadrao = {
            "Farinha de trigo (g)",
            "Açúcar (g)",
            "Ovo (un)",
            "Leite (ml)",
            "Óleo (ml)",
            "Fermento em pó (g)",
            "Sal (g)",
            "Manteiga (g)",
            "Água (ml)",
            "Chocolate em pó (g)"
        };
        
        for (String ingrediente : ingredientesPadrao) {
            SelecaoCategoriaComboBox2.addItem(ingrediente);
        }
    }
    
    private void configureIngredientsTable() {
        tableModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Torna todas as células não editáveis
            }
            
            @Override
            public Class<?> getColumnClass(int columnIndex) {
                // Define o tipo de dado de cada coluna para melhor formatação
                switch (columnIndex) {
                    case 0: return String.class;  // Nome do ingrediente
                    case 1: return Integer.class;  // Quantidade
                    case 2: return String.class;   // Unidade de medida
                    default: return Object.class;
                }
            }
        };
        
        // Configurar as colunas da tabela
        tableModel.addColumn("Ingrediente");
        tableModel.addColumn("Quantidade");
        tableModel.addColumn("Unidade");
        
        // Configurar a tabela
        IngredientesTable.setModel(tableModel);
        
        // Configurar a largura das colunas
        IngredientesTable.getColumnModel().getColumn(0).setPreferredWidth(200);
        IngredientesTable.getColumnModel().getColumn(1).setPreferredWidth(60);
        IngredientesTable.getColumnModel().getColumn(2).setPreferredWidth(80);
        
        // Impedir redimensionamento da tabela
        IngredientesTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        
        // Permitir apenas seleção de uma linha por vez
        IngredientesTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        
        // Remover coluna de índice
        IngredientesTable.getTableHeader().setReorderingAllowed(false);
    }
    
    private void adicionarIngredienteReceita() {
        // Verifica se um ingrediente foi selecionado
        String selecionado = (String) SelecaoCategoriaComboBox2.getSelectedItem();
        if (selecionado == null || selecionado.equals("Selecione um ingrediente") || selecionado.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Selecione um ingrediente.", 
                "Aviso", 
                JOptionPane.WARNING_MESSAGE);
            SelecaoCategoriaComboBox2.requestFocus();
            return;
        }
        
        IngredienteModel ingredienteSelecionado = ingredientesDisponiveis.get(SelecaoCategoriaComboBox2.getSelectedIndex() - 1);
        
        // Valida a quantidade
        try {
            int quantidade = (int) QuantidadeSpinner.getValue();
            if (quantidade <= 0) {
                JOptionPane.showMessageDialog(this, 
                    "A quantidade deve ser maior que zero.", 
                    "Aviso", 
                    JOptionPane.WARNING_MESSAGE);
                QuantidadeSpinner.requestFocus();
                JSpinner.NumberEditor editor = (JSpinner.NumberEditor) QuantidadeSpinner.getEditor();
                JFormattedTextField textField = editor.getTextField();
                textField.setSelectionStart(0);
                textField.setSelectionEnd(textField.getText().length());
                return;
            }
            
            // Verifica se o ingrediente já foi adicionado
            for (ReceitaIngredienteModel ri : ingredientesReceita) {
                if (ri.getIngrediente() != null && 
                    ri.getIngrediente().getNome().equalsIgnoreCase(ingredienteSelecionado.getNome())) {
                    JOptionPane.showMessageDialog(this, 
                        "Este ingrediente já foi adicionado à receita.", 
                        "Aviso", 
                        JOptionPane.WARNING_MESSAGE);
                    return;
                }
            }
            
            // Cria o modelo de ingrediente da receita
            ReceitaIngredienteModel receitaIngrediente = new ReceitaIngredienteModel();
            if (ingredienteSelecionado.getId_ingrediente() > 0) {
                receitaIngrediente.setId_ingrediente(ingredienteSelecionado.getId_ingrediente());
            }
            receitaIngrediente.setQuantidade(quantidade);
            receitaIngrediente.setIngrediente(ingredienteSelecionado);
            
            // Adiciona à lista de ingredientes da receita
            ingredientesReceita.add(receitaIngrediente);
            
            // Atualiza a tabela
            atualizarTabelaIngredientes();
            
            // Limpa os campos e prepara para o próximo ingrediente
            QuantidadeSpinner.setValue(1);
            SelecaoCategoriaComboBox2.setSelectedIndex(0);
            SelecaoCategoriaComboBox2.requestFocus();
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, 
                "Digite um valor numérico válido para a quantidade.", 
                "Erro", 
                JOptionPane.ERROR_MESSAGE);
            QuantidadeSpinner.requestFocus();
            JSpinner.NumberEditor editor = (JSpinner.NumberEditor) QuantidadeSpinner.getEditor();
            JFormattedTextField textField = editor.getTextField();
            textField.setSelectionStart(0);
            textField.setSelectionEnd(textField.getText().length());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Erro ao adicionar ingrediente: " + e.getMessage(), 
                "Erro", 
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
    
    private void atualizarTabelaIngredientes() {
        // Limpar a tabela
        tableModel.setRowCount(0);
        
        // Adicionar cada ingrediente à tabela
        for (ReceitaIngredienteModel ri : ingredientesReceita) {
            if (ri.getIngrediente() != null) {
                tableModel.addRow(new Object[]{
                    ri.getIngrediente().getNome(),
                    ri.getQuantidade(),
                    ri.getIngrediente().getUnidade_medida()
                });
            } else {
                // Se não houver objeto ingrediente, usar os dados básicos
                tableModel.addRow(new Object[]{
                    "Ingrediente #" + ri.getId_ingrediente(),
                    ri.getQuantidade(),
                    "un" // Unidade padrão
                });
            }
        }
        
        // Atualizar a interface
        IngredientesTable.repaint();
        IngredientesTable.revalidate();
    }
    
    private void removerIngredienteReceita() {
        int linhaSelecionada = IngredientesTable.getSelectedRow();
        if (linhaSelecionada < 0 || linhaSelecionada >= ingredientesReceita.size()) {
            JOptionPane.showMessageDialog(this, 
                "Selecione um ingrediente na tabela para remover.", 
                "Aviso", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        ingredientesReceita.remove(linhaSelecionada);
        atualizarTabelaIngredientes();
        
        // Mostra mensagem de sucesso
        JOptionPane.showMessageDialog(this, 
            "Ingrediente removido com sucesso!", 
            "Sucesso", 
            JOptionPane.INFORMATION_MESSAGE);
    }
    
    private void salvarReceita() {
        // Validar campos obrigatórios
        String nome = NomeTextField.getText().trim();
        String descricao = DescricaoTextArea.getText().trim();
        String modoPreparo = ModoPreparoTextArea.getText().trim();
        String categoria = (String) SelecaoCategoriaComboBox1.getSelectedItem();
        
        // Validações básicas
        if (nome.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "O nome da receita é obrigatório.", 
                "Aviso", 
                JOptionPane.WARNING_MESSAGE);
            NomeTextField.requestFocus();
            return;
        }
        
        if (categoria == null || categoria.equals("Selecione uma opção")) {
            JOptionPane.showMessageDialog(this, 
                "Selecione uma categoria válida para a receita.", 
                "Aviso", 
                JOptionPane.WARNING_MESSAGE);
            SelecaoCategoriaComboBox1.requestFocus();
            return;
        }
        
        if (descricao.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "A descrição da receita é obrigatória.", 
                "Aviso", 
                JOptionPane.WARNING_MESSAGE);
            DescricaoTextArea.requestFocus();
            return;
        }
        
        if (modoPreparo.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "O modo de preparo é obrigatório.", 
                "Aviso", 
                JOptionPane.WARNING_MESSAGE);
            ModoPreparoTextArea.requestFocus();
            return;
        }
        
        if (ingredientesReceita.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Adicione pelo menos um ingrediente à receita.", 
                "Aviso", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            ReceitaModel novaReceita = new ReceitaModel();
            novaReceita.setNome(nome);
            novaReceita.setDescricao(descricao);
            novaReceita.setModoPreparo(modoPreparo);
            novaReceita.setCategoria(categoria);
            novaReceita.setIdUsuario(usuarioLogado.getIdUsuario());
            
            for (ReceitaIngredienteModel ingrediente : ingredientesReceita) {
                novaReceita.getListaIngredientes().add(ingrediente);
            }
            
            // Salvar a receita
            boolean sucesso = receitaController.publicarNovaReceita(novaReceita, usuarioLogado);
            
            if (sucesso) {
                JOptionPane.showMessageDialog(this, 
                    "Receita salva com sucesso!", 
                    "Sucesso", 
                    JOptionPane.INFORMATION_MESSAGE);
                
                // Limpar o formulário
                limparFormulario();
            } else {
                JOptionPane.showMessageDialog(this, 
                    "Não foi possível salvar a receita. Verifique os dados e tente novamente.", 
                    "Erro", 
                    JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Erro ao salvar a receita: " + e.getMessage(), 
                "Erro", 
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
    
    private void limparFormulario() {
        NomeTextField.setText("");
        DescricaoTextArea.setText("");
        ModoPreparoTextArea.setText("");
        SelecaoCategoriaComboBox1.setSelectedIndex(0);
        SelecaoCategoriaComboBox2.setSelectedIndex(0);
        QuantidadeSpinner.setValue(1);
        
        // Limpar a lista de ingredientes e a tabela
        ingredientesReceita.clear();
        tableModel.setRowCount(0);
        
        // Voltar o foco para o campo de nome
        NomeTextField.requestFocus();
    }
    
    private void configureModoPreparoAutoWrap() {
        // Adicionar KeyListener no ModoPreparoTextArea para quebra automática de linha
        ModoPreparoTextArea.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyReleased(java.awt.event.KeyEvent evt) {
                processarQuebraLinhaModoPreparo();
            }
        });
    }
    
    private void processarQuebraLinhaModoPreparo() {
        String texto = ModoPreparoTextArea.getText();
        if (texto == null || texto.isEmpty()) {
            return;
        }
        
        // Obter posição do cursor antes da modificação
        int posicaoCursor = ModoPreparoTextArea.getCaretPosition();
        
        // Dividir o texto em linhas
        String[] linhas = texto.split("\n", -1);
        StringBuilder textoFormatado = new StringBuilder();
        boolean textoModificado = false;
        
        for (int i = 0; i < linhas.length; i++) {
            String linha = linhas[i];
            
            // Se a linha tem mais de 35 caracteres, quebrar
            while (linha.length() > 35) {
                // Encontrar o último espaço antes de 35 caracteres para não quebrar palavras
                int posicaoQuebra = 35;
                if (linha.length() > 35) {
                    // Tentar quebrar no último espaço antes de 35 caracteres
                    int ultimoEspaco = linha.lastIndexOf(' ', 35);
                    if (ultimoEspaco > 20) { // Se encontrou espaço razoável (não muito no início)
                        posicaoQuebra = ultimoEspaco;
                    }
                }
                
                // Adicionar a parte até a quebra
                textoFormatado.append(linha.substring(0, posicaoQuebra));
                textoFormatado.append("\n");
                
                // Continuar com o restante da linha
                linha = linha.substring(posicaoQuebra).trim();
                textoModificado = true;
            }
            
            // Adicionar o restante da linha (ou linha completa se <= 35)
            textoFormatado.append(linha);
            
            // Adicionar quebra de linha entre linhas originais (exceto na última)
            if (i < linhas.length - 1) {
                textoFormatado.append("\n");
            }
        }
        
        // Se o texto foi modificado, atualizar o TextArea
        if (textoModificado) {
            String novoTexto = textoFormatado.toString();
            ModoPreparoTextArea.setText(novoTexto);
            
            // Ajustar posição do cursor (aproximadamente)
            int novaPosicao = Math.min(posicaoCursor, novoTexto.length());
            ModoPreparoTextArea.setCaretPosition(novaPosicao);
        }
    }
}
