/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.UsuarioModel;
import model.NivelUsuario;

/**
 *
 * @author rsbuf
 */
public class TelaInformacoes extends javax.swing.JFrame {

    private final model.UsuarioModel usuario;
    
    /**
     * Construtor para criar a tela de informações do usuário
     * @param usuario Usuário logado
     */
    public TelaInformacoes(model.UsuarioModel usuario) {
        this.usuario = usuario;
        initComponents();
        carregarDadosUsuario();
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                voltarParaMenu();
            }
        });
    }
    
    /**
     * Carrega os dados do usuário nos campos da tela
     */
    private void carregarDadosUsuario() {
        if (usuario != null) {
            // Atualiza o título com o nome do usuário
            TituloLabel.setText(usuario.getNome());
            
            // Preenche os campos com as informações do usuário
            NomeLabel.setText("Nome: " + usuario.getNome());
            EmailLabel.setText("Email: " + usuario.getEmail());
            
            // Para a senha, mostramos apenas asteriscos
            SenhaLabel.setText("Senha: ********");
            
            // Exibimos o nível e a pontuação
            NivelContaLabel.setText("Nível: " + usuario.getNivel());
            PontuacaoLabel.setText("Pontuação: " + usuario.getPontuacao());
        }
    }
    
    /**
     * Volta para o menu principal
     */
    private void voltarParaMenu() {
        MenuView menu = new MenuView(usuario);
        menu.setVisible(true);
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        TituloPanel = new javax.swing.JPanel();
        TituloLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        NomeLabel = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        SenhaLabel = new javax.swing.JLabel();
        NivelContaLabel = new javax.swing.JLabel();
        PontuacaoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TituloPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TituloPanel.setLayout(new java.awt.GridBagLayout());

        TituloLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TituloLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloLabel.setText("-Conta usuario-");
        TituloLabel.setFocusCycleRoot(true);
        TituloLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 51, 17, 51);
        TituloPanel.add(TituloLabel, gridBagConstraints);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        NomeLabel.setText("Nome:");

        EmailLabel.setText("Email:");

        SenhaLabel.setText("Senha:");

        NivelContaLabel.setText("Nivel da Conta:");

        PontuacaoLabel.setText("Pontuação:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PontuacaoLabel)
                    .addComponent(NivelContaLabel)
                    .addComponent(SenhaLabel)
                    .addComponent(EmailLabel)
                    .addComponent(NomeLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(NomeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EmailLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SenhaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NivelContaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PontuacaoLabel)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TituloPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(TituloPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInformacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInformacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInformacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInformacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // Criando um usuário de exemplo para teste
                // Em produção, você deve passar o usuário logado
                UsuarioModel usuarioExemplo = new UsuarioModel();
                usuarioExemplo.setNome("Usuário de Teste");
                usuarioExemplo.setEmail("teste@exemplo.com");
                // Definindo um nível padrão
                usuarioExemplo.setNivel(NivelUsuario.INICIANTE);
                usuarioExemplo.setPontuacao(100);
                
                new TelaInformacoes(usuarioExemplo).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JLabel NivelContaLabel;
    private javax.swing.JLabel NomeLabel;
    private javax.swing.JLabel PontuacaoLabel;
    private javax.swing.JLabel SenhaLabel;
    private javax.swing.JLabel TituloLabel;
    private javax.swing.JPanel TituloPanel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
